name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
    simple_deployment_pipeline:
        if: ${{ github.event_name == 'push' }}
        runs-on: ubuntu-20.04
        permissions: # Required if github_deployment is set to true.
          deployments: write
        steps:
          - uses: actions/checkout@v3
          - uses: actions/setup-node@v3
            with:
              node-version: '16'

          - name: Install dependencies
            run: cd frontend && npm install

          - name: lint
            run: npm run eslint

          - name: Check build
            run: npm run build
