name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
    simple_deployment_pipeline:
        runs-on: ubuntu-20.04
        steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-node@v3
            with:
              node-version: '16'

          - name: Install dependencies
            run: cd frontend && npm install

          - name: lint
            run: cd frontend && npm run eslint

          - name: Check build
            run: cd frontend && npm run build

          - name: e2e tests
            uses: cypress-io/github-action@v5
            with:
              command: cd frontend && npm run test:e2e
              start: cd backend && npm run start
              wait-on: http://localhost:3003
